spring:
  application:
    name: user-service
  datasource:
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: true
  flyway:
    enabled: false
